# -*- coding: utf-8 -*-
"""Importer&manipuler-des-fichiers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NdsyYgQGzUtVoGi4kscZ4J-eZnYgrD-a

** Importer un fichier **

Nous avons un fichier `identite.txt` dans le dossier `datasets` qui contient des informations relatives à l'identité d'un utilisateur. Ce fichier contient 6 lignes et dans l'ordre on a :
* nom
* prenom
* pays d'origine
* pays de residence
* age
* sexe

L'objectif est d'importer le fichier et d'afficher un message personnalisé à notre utilisateur.


Nous avons d'abord besoin du chemin de notre fichier, que ce soit sur Google drive ou en local
"""

fichier = '/identite.txt'

""" On demande Python d'ouvrir notre fichier en mode lecture( `'r'`) et de le nommer f. A la seconde ligne, nous utilisons `f.readlines()` pour importer les lignes de nos fichiers. Affichons les lignes:"""

with open(fichier, 'r') as f:
    lines = f.readlines()

lines

"""*['Degila\n', 'Kevin\n', 'Benin\n', 'Maroc\n', '24\n', 'Masculin\n']*

On peut voir le contenu de chaque ligne et les sauts de lignes représenté par les \n. On peut les effacer:
"""

for i, line in enumerate(lines):
    lines[i] = line.replace('\n', '')
print(lines)

nom = lines[0]
prenom = lines[1]
age = lines[-2]

salutation = f'Bonjour {prenom} {nom}. Vous avez {age} ans.'
print(salutation)

"""**Ecrire dans un fichier avec Python**

 générer un fichier correspondant à chaque fichier identité qu'on recoit. Ce fichier contiendra notre message de salutation et s'appellera `{nom}.txt`. Il nous faut specifier le chemin du fichier: là où on souhaite le stocker
"""

chemin_du_fichier = f'/{nom}.txt'

with open(chemin_du_fichier, 'w') as f:
    f.write(salutation)

"""Comparer à la section précédente, ce qui a changé c'est qu'on a ouvert le fichier en mode écriture avec `'w'` et avons utilisé la fonction `f.write()` pour écrire dans le fichier. Dans notre dossier dataset se trouve désormais un fichier `Degila.txt` qui contient la salutation"""