# -*- coding: utf-8 -*-
"""input&conditions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VpV8m2YQPqa6GKVFhcoUEY-rmW2aiLej

**Recevoir des données de l'utilisateur**

1 - la fonction INPUT()
"""

nom = input("Quel est ton nom : ")
nom

"""demande d'un mot de passe"""

username = input("Quel est ton nom d'utilisateur: ")
password = input("Quel est ton mot de passe: ")
print("Bonjour ",username, " Votre mot de passe n'est pas sécurisé pour le moment. Je peux le lire, c'est : ", password)

"""Une question :  Quel est le type de la donnée qu'on reçoit ?"""

age = input("Quel est ton age: ")
type(age)
age

type(age)

age = int(age)

age

type(age)

age = int(input("Quel est ton age: "))

age

type(age)

"""**PRENDRE DES DECISIONS**

**Conditions**

Une condition en programmation: C'est une question dont la réponse est Vrai (`True`) ou Faux (`False`).

Exemple : Est-ce que l'age de l'utilisateur est supérieur à 15 ? Est-ce que la liste a moins de 5 éléments ?
"""

n = 25
n > 36

n<18

n == 25

n != 25

n <= 15.56

langage = "Python"
langage == "Javascript"

len(langage) > 5

'n' in langage

langage.startswith('Py')

langage.endswith('C')

fruits = ["Pomme", "avocat", "ananas"]
len(fruits)>5

fruits[0] == 'Pomme'

"""Et si on posait plusieurs questions en même temps à notre ordinateur du genre:
* Est-ce la note d'un étudiant est entre 10 et 12, donc inférieur à 12 et supérieur à 10 ?
* Est-ce qu'il y a 10 élements dans la liste et est-ce que "bob" est dans la liste ?
* Est-ce que "kevin" ou "kevindegila" est dans l'annuaire ?
"""

note = 11
note > 12

note< 10

note > 12 and note < 10

note > 10 and note < 12

"""**Si.. Sinon si .. Sinon..**

1 Demander à notre programme  d'afficher "Reussite" quand la note est supérieure à 10:
"""

note = int(input('quelle est votre note:'))

note

note > 10

"""2 On rajoute une condition


```
# if condition:
      action

```
"""

note = int(input('Quelle est votre note : '))

if note > 10:
    print("Reussite")

"""L'action est donc réalisé uniquement si la condition est vraie. Verifions si on n'a l'affichage avec une condition qui est fausse avec "else"
"""

if note < 10:
    print("Reussite")
else:
    print("Echec")

if 0 < note < 10:
    print("Mention Insuffisante")
elif 10 <= note < 12:
    print("Mention Passable")
elif 12 <= note < 15:
    print('Mention Assez bien')
elif 15 <= note < 17:
    print("Mention Bien")
else:
    print('Excellent.')

username = input("Quel est ton nom d'utilisateur: ")
password = input("Quel est ton mot de passe: ")
second_password = input("Entrez le mot de passe une seconde fois : ")

if password == second_password:
    print("Vous êtes inscrits !!!")
else:
    print("Votre second mot de passe n'est pas égale au premier'. Réessayer")

username = input("Quel est ton nom d'utilisateur: ")
password = input("Quel est ton mot de passe: ")
second_password = input("Entrez le mot de passe une seconde fois : ")

if password == second_password:
    print("Vous êtes inscrits !!!")
else:
    print("Votre second mot de passe n'est pas égale au premier'. Réessayer")

