# -*- coding: utf-8 -*-
"""Les fonctions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AN72mhYOwitdtWePRmKX8pog10pOJ_Y_

**Les fonctions**



1.   Replace : remplace une partie d'une chaine de caractères
2.   Listdir : Accéder au chemin
3.   randint : génère un nombre aléatoire dans un intervalle donné
"""

"Hello Python".replace('Hello', 'Bonjour')

"""La syntaxe d'une fonction est la suivante:
```python
def nom_de_la_fonction(paramètres):
    code qui explique ce que fait la fonction
    return quelque chose
```
Le mot clé `def` dit à python que le code indenté ci-dessous est une fonction et le mot clé `return` permet de retourner le résultat de la fonction. On peut avoir plusieurs `return` dans une fonction mais dès qu'un est éxécuté, la fonction est terminée . Une fonction ne retourne pas forcément quelque chose. Dans ces cas, on peut simplement ommetre le mot clé return.
"""

def est_pair(nombre):
    if nombre % 2 == 0: # si reste de la division de nombre par 2 est 0
        return True     # retourne Vrai et fonction terminée
    return False # sinon retourne Faux et fonction terminée
resultat = est_pair(5)
print(resultat)

def salutation(nom):
    message = f"Bonjour {nom}. J'espère que vous passez une bonne journée"
    return message
salutation("Bob")

def grandir(nom, age):
    message = f'Bonjour {nom}, vous avez grandi. Vous avez désormais {age + 1} ans'
    return message
m = grandir('Bob', 15)
m

"""**Les modules**

Python vient avec un nombre enorme de fonctions utiles. Ces fonctions sont dans un fichier python comme par exemple `os.py`. On peut importer ces fonctions tout simplement avec le mot clé **import**.

Le module os permet d'interagir avec notre système d'opération, donc de copier, créer, déplacer, supprimer des fichiers et documents grâce à des fonctions dédiées. Importons le module os:
"""

import os

os.listdir('./') # le chemin relatif du dossier

from random import randint

randint(0, 100)